### ISSUE TITLE
Homebrew supports

### ISSUE THREAD

**Issue by ccoVeille** [kardwen/passepartui#11]
I love your tool. Do you think you could provide it through homebrew

It would help people on Linux (like me) and people on macOS to get the last version of your tool easily.

Relying cargo is never fun

**Comment by ccoVeille** [comment]
Amazing, this is already enough in fact

```console
brew tap kardwen/passepartui
brew install passepartui
```

Please note, the following is enough

```console
brew install kardwen/passepartui/passepartui
```

The fact people using your tool can already use homebrew is already a game changer I think.

So, now it's up to you to decide if you want to make your app adoption faster via the homebrew community. This will bring your app available to anyone. It will pop out as new app, can be found via the brew search command.

**Comment by kardwen** [comment]
`brew install kardwen/passepartui/passepartui` doesn't work for me, no idea why...

I think I will add a section for Homebrew to the README and maybe automate updating `homebrew-passepartui` whenever there is a new release.

**Comment by kardwen** [comment]
I added a hint to the README for installation via Homebrew
