### ISSUE TITLE
How do I add a Password?

### ISSUE THREAD

**Issue by kaanboraoz** [kardwen/passepartui#2]
I ran it locally and added a “notes” field because I want to contribute, but I don't know how to add a password to the application, can you help me :)😄

**Comment by kardwen** [comment]
Hey, this project uses `pass` for organizing passwords, I might write a short introduction later. Currently you can't add a password with the TUI, but you can ran for example run `pass generate your-password-file`.

Here you can find a good writeup for now: <https://wiki.archlinux.org/title/Pass>

A password store is essentially just a directory of `gpg` encrypted files. The convention for files is to use the first line for your password and the second for login. I am not sure if there is a convention for where to add a note. I have seen versions where the password and login is prefixed with `password: ` and `login :`, but currently `passepartui` does not differentiate between this.

If you press (i) in passepartui, you can see the file contents. Maybe just add a note for passwords in a new line?

**Comment by kaanboraoz** [comment]
Thanks for your explanation and help, I'm pretty new so I apologize if I stole your time man

**Comment by kardwen** [comment]
No problem, it actually helped to find out where the README was missing some informations. Thanks!
